/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;
    public SupplierWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendingOrdersBtn = new javax.swing.JButton();
        manageInventoryBtn = new javax.swing.JButton();
        placedOrdersBtn = new javax.swing.JButton();
        viewReportBtn = new javax.swing.JButton();
        manageCatalogBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pendingOrdersBtn.setBackground(new java.awt.Color(51, 51, 51));
        pendingOrdersBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        pendingOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        pendingOrdersBtn.setText("View Pending Orders >>");
        pendingOrdersBtn.setBorder(new javax.swing.border.MatteBorder(null));
        pendingOrdersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendingOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendingOrdersBtnActionPerformed(evt);
            }
        });

        manageInventoryBtn.setBackground(new java.awt.Color(51, 51, 51));
        manageInventoryBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        manageInventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageInventoryBtn.setText("Manage Warehouse >>");
        manageInventoryBtn.setBorder(new javax.swing.border.MatteBorder(null));
        manageInventoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryBtnActionPerformed(evt);
            }
        });

        placedOrdersBtn.setBackground(new java.awt.Color(51, 51, 51));
        placedOrdersBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        placedOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        placedOrdersBtn.setText("View Placed Orders >>");
        placedOrdersBtn.setBorder(new javax.swing.border.MatteBorder(null));
        placedOrdersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        placedOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placedOrdersBtnActionPerformed(evt);
            }
        });

        viewReportBtn.setBackground(new java.awt.Color(51, 51, 51));
        viewReportBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        viewReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewReportBtn.setText("View Report >>");
        viewReportBtn.setBorder(new javax.swing.border.MatteBorder(null));
        viewReportBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportBtnActionPerformed(evt);
            }
        });

        manageCatalogBtn.setBackground(new java.awt.Color(51, 51, 51));
        manageCatalogBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        manageCatalogBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageCatalogBtn.setText("Manage Product Catalog >>");
        manageCatalogBtn.setBorder(new javax.swing.border.MatteBorder(null));
        manageCatalogBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageCatalogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCatalogBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Supplier Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/SupplierRole/supplier.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageInventoryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placedOrdersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pendingOrdersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewReportBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1)
                        .addGap(117, 117, 117)
                        .addComponent(manageCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(manageCatalogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(manageInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(placedOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(pendingOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(viewReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)))
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryBtnActionPerformed
        ManageInventoryJPanel manageInventorySupplierJPanel = new ManageInventoryJPanel(userProcessContainer, account, enterprise, network);
        userProcessContainer.add("manageInventorySupplierJPanel", manageInventorySupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInventoryBtnActionPerformed

    private void placedOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placedOrdersBtnActionPerformed
        ViewOrdersJPanel viewOrdersSupplierJPanel = new ViewOrdersJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("viewOrdersSupplierJPanel", viewOrdersSupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_placedOrdersBtnActionPerformed

    private void viewReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportBtnActionPerformed
        ViewReportJPanel viewReportSupplierJPanel = new ViewReportJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("viewReportSupplierJPanel", viewReportSupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReportBtnActionPerformed

    private void pendingOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendingOrdersBtnActionPerformed
        PendingOrdersJPanel pendingOrdersSupplierJPanel = new PendingOrdersJPanel(userProcessContainer, account, enterprise, network);
        userProcessContainer.add("pendingOrdersSupplierJPanel", pendingOrdersSupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_pendingOrdersBtnActionPerformed

    private void manageCatalogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCatalogBtnActionPerformed
        ManageProductsJPanel manageProductsSupplierJPanel = new ManageProductsJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("manageProductsSupplierJPanel", manageProductsSupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCatalogBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageCatalogBtn;
    private javax.swing.JButton manageInventoryBtn;
    private javax.swing.JButton pendingOrdersBtn;
    private javax.swing.JButton placedOrdersBtn;
    private javax.swing.JButton viewReportBtn;
    // End of variables declaration//GEN-END:variables
}
