/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author user
 */

public class FarmerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    private Network network;
    public FarmerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewReportBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        manageOrdersJPanel = new javax.swing.JButton();
        manageProductsBtn = new javax.swing.JButton();
        manageInventoryJPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        viewReportBtn.setBackground(new java.awt.Color(51, 51, 51));
        viewReportBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        viewReportBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewReportBtn.setText("View Report >>");
        viewReportBtn.setBorder(new javax.swing.border.MatteBorder(null));
        viewReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("My Work Area - Farmer Role");

        manageOrdersJPanel.setBackground(new java.awt.Color(51, 51, 51));
        manageOrdersJPanel.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        manageOrdersJPanel.setForeground(new java.awt.Color(255, 255, 255));
        manageOrdersJPanel.setText("Manage All Orders >>");
        manageOrdersJPanel.setBorder(new javax.swing.border.MatteBorder(null));
        manageOrdersJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJPanelActionPerformed(evt);
            }
        });

        manageProductsBtn.setBackground(new java.awt.Color(51, 51, 51));
        manageProductsBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        manageProductsBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageProductsBtn.setText("Manage Product Catalog >>");
        manageProductsBtn.setBorder(new javax.swing.border.MatteBorder(null));
        manageProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsBtnActionPerformed(evt);
            }
        });

        manageInventoryJPanel.setBackground(new java.awt.Color(51, 51, 51));
        manageInventoryJPanel.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        manageInventoryJPanel.setForeground(new java.awt.Color(255, 255, 255));
        manageInventoryJPanel.setText("Manage Warehouse >>");
        manageInventoryJPanel.setBorder(new javax.swing.border.MatteBorder(null));
        manageInventoryJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryJPanelActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/FarmerRole/corn_farmer.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(manageProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manageOrdersJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(viewReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manageInventoryJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel2)))
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageInventoryJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageOrdersJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportBtnActionPerformed
        ViewReportJPanel viewReportFarmJPanel = new ViewReportJPanel(userProcessContainer, account, enterprise);
        userProcessContainer.add("viewReportFarmJPanel", viewReportFarmJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReportBtnActionPerformed

    private void manageOrdersJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJPanelActionPerformed
        ManageOrderJPanel manageOrderFarmJPanel = new ManageOrderJPanel(userProcessContainer, account, enterprise, network);
        userProcessContainer.add("manageOrderFarmJPanel", manageOrderFarmJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersJPanelActionPerformed

    private void manageProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsBtnActionPerformed
        ManageProductsJPanel manageProductsFarmJPanel = new ManageProductsJPanel(userProcessContainer, account);
        userProcessContainer.add("manageProductsFarmJPanel", manageProductsFarmJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProductsBtnActionPerformed

    private void manageInventoryJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryJPanelActionPerformed
        ManageInventoryJPanel manageInventoryFarmJPanel = new ManageInventoryJPanel(userProcessContainer, account);
        userProcessContainer.add("manageInventoryFarmJPanel", manageInventoryFarmJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInventoryJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageInventoryJPanel;
    private javax.swing.JButton manageOrdersJPanel;
    private javax.swing.JButton manageProductsBtn;
    private javax.swing.JButton viewReportBtn;
    // End of variables declaration//GEN-END:variables
}
