/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FDARole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CustomerWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PendingComplaintJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PendingComplaintJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private Network network;

    public PendingComplaintJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        populateComplaintTable();
    }

    public void populateComplaintTable() {
        DefaultTableModel model = (DefaultTableModel) complaintTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            CustomerWorkRequest custWorkRequest = (CustomerWorkRequest) request;
            
                Object[] row = new Object[5];
                row[0] = custWorkRequest;
                row[1] = custWorkRequest.getRfid();
                row[2] = request.getRequestDate();
                row[3] = request.getSender();
                row[4] = request.getStatus();

                model.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        complaintTable = new javax.swing.JTable();
        trackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        retailerTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        retSoldTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        supplierTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        suppSoldTxtField = new javax.swing.JTextField();
        farmerTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        farSoldTxtField = new javax.swing.JTextField();
        resolveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        retailerBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        farmerBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        complaintTable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        complaintTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "RFID", "Request Date", "Customer", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(complaintTable);

        trackBtn.setBackground(new java.awt.Color(51, 51, 51));
        trackBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        trackBtn.setForeground(new java.awt.Color(255, 255, 255));
        trackBtn.setText("Track This Item");
        trackBtn.setBorder(new javax.swing.border.MatteBorder(null));
        trackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Retailer:");

        retailerTxtField.setEditable(false);
        retailerTxtField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        retailerTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retailerTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Supplier:");

        retSoldTxtField.setEditable(false);
        retSoldTxtField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Farmer:");

        supplierTxtField.setEditable(false);
        supplierTxtField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Sold by Retailer On:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Sold by Supplier On:");

        suppSoldTxtField.setEditable(false);
        suppSoldTxtField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        suppSoldTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppSoldTxtFieldActionPerformed(evt);
            }
        });

        farmerTxtField.setEditable(false);
        farmerTxtField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Sold by Farmer On:");

        farSoldTxtField.setEditable(false);
        farSoldTxtField.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        resolveBtn.setBackground(new java.awt.Color(51, 51, 51));
        resolveBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        resolveBtn.setForeground(new java.awt.Color(255, 255, 255));
        resolveBtn.setText("Resolve This Issue >>");
        resolveBtn.setBorder(new javax.swing.border.MatteBorder(null));
        resolveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolveBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(51, 51, 51));
        backBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<< Back");
        backBtn.setBorder(new javax.swing.border.MatteBorder(null));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        retailerBtn.setBackground(new java.awt.Color(51, 51, 51));
        retailerBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        retailerBtn.setForeground(new java.awt.Color(255, 255, 255));
        retailerBtn.setText("Retailer Details");
        retailerBtn.setBorder(new javax.swing.border.MatteBorder(null));
        retailerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retailerBtnActionPerformed(evt);
            }
        });

        supplierBtn.setBackground(new java.awt.Color(51, 51, 51));
        supplierBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        supplierBtn.setForeground(new java.awt.Color(255, 255, 255));
        supplierBtn.setText("Supplier Details");
        supplierBtn.setBorder(new javax.swing.border.MatteBorder(null));
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });

        farmerBtn.setBackground(new java.awt.Color(51, 51, 51));
        farmerBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        farmerBtn.setForeground(new java.awt.Color(255, 255, 255));
        farmerBtn.setText("Farmer Details");
        farmerBtn.setBorder(new javax.swing.border.MatteBorder(null));
        farmerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farmerBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Pending List of Complaints");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(212, 212, 212))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(72, 72, 72))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addGap(74, 74, 74))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retailerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retSoldTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suppSoldTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(farmerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(farSoldTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resolveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(retailerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(supplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(farmerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(retailerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retailerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retSoldTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppSoldTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farmerTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farmerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farSoldTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(resolveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackBtnActionPerformed
        int selectedRow = complaintTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        CustomerWorkRequest request = (CustomerWorkRequest) complaintTable.getValueAt(selectedRow, 0);

        retailerTxtField.setText(request.getRfid().getRetailer().getPerson().getName());
        retSoldTxtField.setText(String.valueOf(request.getRfid().getProductSoldDate()));
        supplierTxtField.setText(request.getRfid().getSupplier().getPerson().getName());
        suppSoldTxtField.setText(String.valueOf(request.getRfid().getSupplierShippingDate()));
        farmerTxtField.setText(request.getRfid().getFarmer().getPerson().getName());
        farSoldTxtField.setText(String.valueOf(request.getRfid().getFarmerShippingDate()));


    }//GEN-LAST:event_trackBtnActionPerformed

    private void retailerTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retailerTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retailerTxtFieldActionPerformed

    private void suppSoldTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppSoldTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppSoldTxtFieldActionPerformed

    private void resolveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolveBtnActionPerformed
        int selectedRow = complaintTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        CustomerWorkRequest request = (CustomerWorkRequest) complaintTable.getValueAt(selectedRow, 0);

        request.setStatus("Processing");

        ResolveComplaintJPanel resolveComplaintFDAJPanel = new ResolveComplaintJPanel(userProcessContainer, account, network, request, this);
        userProcessContainer.add("resolveComplaintFDAJPanel", resolveComplaintFDAJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_resolveBtnActionPerformed

    private void retailerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retailerBtnActionPerformed
        int selectedRow = complaintTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        CustomerWorkRequest request = (CustomerWorkRequest) complaintTable.getValueAt(selectedRow, 0);
        UserAccount ua = request.getRfid().getRetailer();
        MoreDetailsJPanel moreDetailsFDAJPanel = new MoreDetailsJPanel(userProcessContainer, ua);
        userProcessContainer.add("moreDetailsFDAJPanel", moreDetailsFDAJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_retailerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        int selectedRow = complaintTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        CustomerWorkRequest request = (CustomerWorkRequest) complaintTable.getValueAt(selectedRow, 0);
        UserAccount ua = request.getRfid().getSupplier();
        MoreDetailsJPanel moreDetailsFDAJPanel = new MoreDetailsJPanel(userProcessContainer, ua);
        userProcessContainer.add("moreDetailsFDAJPanel", moreDetailsFDAJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void farmerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farmerBtnActionPerformed
        int selectedRow = complaintTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        CustomerWorkRequest request = (CustomerWorkRequest) complaintTable.getValueAt(selectedRow, 0);
        UserAccount ua = request.getRfid().getFarmer();
        MoreDetailsJPanel moreDetailsFDAJPanel = new MoreDetailsJPanel(userProcessContainer, ua);
        userProcessContainer.add("moreDetailsFDAJPanel", moreDetailsFDAJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_farmerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable complaintTable;
    private javax.swing.JTextField farSoldTxtField;
    private javax.swing.JButton farmerBtn;
    private javax.swing.JTextField farmerTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resolveBtn;
    private javax.swing.JTextField retSoldTxtField;
    private javax.swing.JButton retailerBtn;
    private javax.swing.JTextField retailerTxtField;
    private javax.swing.JTextField suppSoldTxtField;
    private javax.swing.JButton supplierBtn;
    private javax.swing.JTextField supplierTxtField;
    private javax.swing.JButton trackBtn;
    // End of variables declaration//GEN-END:variables
}
